package fullchests.reference;

import cpw.mods.fml.common.ModMetadata;

import java.util.Arrays;

public class Metadata
{
    /**
     * Setup mod metadata
     *
     * @param metadata metadata
     * @return edited metadata object
     */
    public static ModMetadata init(ModMetadata metadata)
    {
        metadata.modId = Reference.ID;
        metadata.name = Reference.NAME;
        metadata.description = Reference.DESCRIPTION;
        //metadata.url = "";
        //metadata.logoFile = "assets/" + Reference.ID + "/logo.png";
        metadata.version = Reference.VERSION_FULL;
        metadata.authorList = Arrays.asList(Reference.AUTHORS);
        //metadata.credits = "";
        metadata.autogenerated = false;
        return metadata;
    }
}
